server.port=8081
spring.application.name=ms-produit

# Keycloak configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/microservices-demo
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/microservices-demo/protocol/openid-connect/certs